### ISSUE TITLE
Crosshair stops updating when auto-aiming

### ISSUE THREAD

**Issue by nxshock** [Pruszko/DispersionReticle#4]
English:
If you use the auto-aim function, then the sight stops updating (neither the position of the sight nor the size of the circle of information changes). After disabling auto-aim, everything starts working as expected.
Tested on version 2.0

Original:
Если использовать функцию автоприцеливания, то прицел перестаёт обновляться (не изменяется ни положение прицела, ни размер круга сведения). После отключения автоприцеливания всё начинает работать как положено.
Проверено на версии 2.0

**Comment by Pruszko** [comment]
Ok, as I see, latency reticle and server reticle doesn't get updated properly on auto aim

**Comment by Pruszko** [comment]
Issue has been fixed in version 2.0.1, also updated version is coming to wgmods as well
