### ISSUE TITLE
Simple Server Reticle Option not working

### ISSUE THREAD

**Issue by Zavars** [Pruszko/DispersionReticle#5]
Hi Pruszko,

Using v2.4.0 the Simple Server Reticle does not seem to work. See attached config (.txt extension added to be able to upload). This config works fine with v2.3.0.

Thank You for the great mod!

[config.json.txt](https://github.com/Pruszko/DispersionReticle/files/12443976/config.json.txt)

**Comment by Fierioziy** [comment]
Hi Zavars, thanks for info.

I've made a small mistake around this reticle toggle.
`Simple Server Reticle` is enabled by `Latency Reticle` toggle (lol), so just enable this reticle with `Hide standard reticle` option for temporary fix.

I'll make a patch that account this bug

**Comment by Pruszko** [comment]
Hi Zavars, thanks for info.

I've made a small mistake around this reticle toggle.
`Simple Server Reticle` is enabled by `Latency Reticle` toggle (lol), so just enable this reticle with `Hide standard reticle` option for temporary fix.

I'll make a patch that account this bug

**Comment by Pruszko** [comment]
Fixed in version 2.4.1

**Comment by Zavars** [comment]
Thanks so much for the fix. I tried it and working great!

Is there potential in an upcoming version that you could add additional configuration parameters (even just in the config file) for the Simple Server Reticle Pentagon & T-Shape options?

For example:
   Pentagon:
      elementScale = 2.0
      circleRadius = 0.75
   T-Shape:
      elementThickness = 0.75
      elementLength = 4
      circleRadius = 0.75

**Comment by Pruszko** [comment]
I can think about it; the only problem would be representing that in config file or in mod configurator

I'll close this issue and make new one with that feature request
