### ISSUE TITLE
Simple server reticle - center dot

### ISSUE THREAD

**Issue by Zavars** [Pruszko/DispersionReticle#8]
In recent versions the center dot for the Simple Server reticle was removed due to it overlapping with the penetration indicator. For my personal config I  had changed the blend and alpha values to mostly overcome this (blend = 0.75, alpha = 1.0).

Would it be possible to add an option so that the center dot can be enabled/disabled?

**Comment by Pruszko** [comment]
Probably yes, in free time I'll add it again with toggle

**Comment by Pruszko** [comment]
Added in 2.6.0
